#!/usr/bin/env python3
"""Deterministic browser-free acceptance suite for Phase 1 stability work.

The suite exercises the batch state machine with a fake ChatGPT provider and
then renders real PDFs with WeasyPrint/PyPDF. It is intended for release
validation, CI, and local upgrade checks; it does not use a real browser or
ChatGPT account.
"""
from __future__ import annotations

import argparse
import json
import tempfile
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable
from unittest import mock

from pypdf import PdfReader

import batch_pdf
import convert_md_to_pdf
import create_combined_pdf


PROJECT_ROOT = Path(__file__).resolve().parent.parent


VALID_NOTE = """# {title}

## Explanation

This deterministic acceptance note contains enough explanatory material to
pass the Markdown artifact validator and exercise the complete Phase 1 flow.
It is generated by the browser-free fake provider used only for release tests.

## Key Points

- Atomic artifact replacement is enabled.
- Manifest state is recorded with hashes.
- Resume skips completed and unchanged jobs.
"""


@dataclass(frozen=True)
class CheckResult:
    name: str
    passed: bool
    duration_seconds: float
    details: str


class FakeDriver:
    """Small Selenium stand-in used by diagnostics and retry orchestration."""

    title = "ChatGPT Acceptance Driver"
    page_source = "<html><body>acceptance fixture</body></html>"

    def save_screenshot(self, path: str) -> bool:
        Path(path).write_bytes(b"acceptance-png")
        return True

    def quit(self) -> None:
        return None


class AcceptanceFailure(RuntimeError):
    pass


def _assert(condition: bool, message: str) -> None:
    if not condition:
        raise AcceptanceFailure(message)


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_candidate(root: Path, name: str, text: str) -> Path:
    candidate_dir = root / "downloads"
    candidate_dir.mkdir(parents=True, exist_ok=True)
    candidate = candidate_dir / name
    candidate.write_text(text, encoding="utf-8")
    return candidate


def _outline_titles(value) -> list[str]:
    titles: list[str] = []
    if isinstance(value, list):
        for item in value:
            titles.extend(_outline_titles(item))
    else:
        title = getattr(value, "title", None)
        if title:
            titles.append(str(title))
    return titles


def _uri_annotations(reader: PdfReader) -> list[str]:
    uris: list[str] = []
    for page in reader.pages:
        for ref in page.get("/Annots") or []:
            annotation = ref.get_object()
            action = annotation.get("/A")
            if action and action.get("/S") == "/URI":
                uri = action.get("/URI")
                if uri:
                    uris.append(str(uri))
    return uris


class Phase1Acceptance:
    def __init__(self, workspace: Path) -> None:
        self.workspace = Path(workspace).resolve()
        self.workspace.mkdir(parents=True, exist_ok=True)
        self.checks: list[CheckResult] = []
        self.notes_dir = self.workspace / "outputs" / "notes"
        self.logs_dir = self.workspace / "logs"
        self.prompt = self.workspace / "prompt.md"
        self.input_dir = self.workspace / "inputs"

    def _run_check(self, name: str, callback: Callable[[], str]) -> None:
        started = time.perf_counter()
        try:
            details = callback()
        except Exception as exc:  # noqa: BLE001 - report the exact acceptance failure
            self.checks.append(
                CheckResult(
                    name=name,
                    passed=False,
                    duration_seconds=round(time.perf_counter() - started, 4),
                    details=f"{type(exc).__name__}: {exc}",
                )
            )
        else:
            self.checks.append(
                CheckResult(
                    name=name,
                    passed=True,
                    duration_seconds=round(time.perf_counter() - started, 4),
                    details=details,
                )
            )

    def run(self) -> dict:
        self._run_check("batch_failure_and_diagnostics", self._check_initial_failure)
        if self.checks[-1].passed:
            self._run_check("retry_failed_and_resume", self._check_retry_and_resume)
        else:
            self.checks.append(
                CheckResult(
                    name="retry_failed_and_resume",
                    passed=False,
                    duration_seconds=0.0,
                    details="Skipped because the initial batch check failed.",
                )
            )
        if self.checks[-1].passed:
            self._run_check("pdf_book_end_to_end", self._check_pdf_book)
        else:
            self.checks.append(
                CheckResult(
                    name="pdf_book_end_to_end",
                    passed=False,
                    duration_seconds=0.0,
                    details="Skipped because note generation/recovery did not complete.",
                )
            )

        passed = all(check.passed for check in self.checks)
        return {
            "schema_version": 1,
            "phase": "phase1-stability",
            "version": (PROJECT_ROOT / "VERSION").read_text(encoding="utf-8").strip(),
            "created_at": datetime.now(timezone.utc).isoformat(),
            "workspace": str(self.workspace),
            "passed": passed,
            "checks": [asdict(check) for check in self.checks],
        }

    def _base_patches(self, driver: FakeDriver):
        return (
            mock.patch.object(batch_pdf.common, "LOGS_DIR", self.logs_dir),
            mock.patch.object(batch_pdf.core, "LOG_FILE", self.workspace / "run.log"),
            mock.patch.object(batch_pdf.common, "bootstrap_session", return_value=driver),
            mock.patch.object(batch_pdf.common, "driver_is_alive", return_value=True),
            mock.patch.object(batch_pdf.common, "reset_chat"),
            mock.patch.object(batch_pdf.common, "prune_driver_cookies"),
            mock.patch.object(batch_pdf.common.time, "sleep"),
            mock.patch.object(batch_pdf.core, "latest_assistant_text", return_value="acceptance fixture response"),
        )

    def _prepare_sources(self) -> None:
        self.input_dir.mkdir(parents=True, exist_ok=True)
        self.notes_dir.mkdir(parents=True, exist_ok=True)
        (self.input_dir / "01_First.pdf").write_bytes(b"acceptance-pdf-one")
        (self.input_dir / "02_Second.pdf").write_bytes(b"acceptance-pdf-two")
        self.prompt.write_text("Create a structured Markdown study note.", encoding="utf-8")

    def _check_initial_failure(self) -> str:
        self._prepare_sources()
        driver = FakeDriver()
        calls: dict[str, int] = {}

        def fake_process(_driver, _prompt, input_path, output_dir, _model, **kwargs):
            calls[input_path.name] = calls.get(input_path.name, 0) + 1
            output_path = output_dir / f"{input_path.stem}.{kwargs['output_ext'].lstrip('.')}"
            if input_path.name == "01_First.pdf":
                candidate = _write_candidate(
                    self.workspace,
                    "01_First.md",
                    VALID_NOTE.format(title="First Acceptance Topic"),
                )
            else:
                candidate = _write_candidate(self.workspace, "02_Second.md", "# incomplete")
            batch_pdf.common.save_artifact_download(candidate, output_path)
            return True

        patches = self._base_patches(driver)
        with patches[0], patches[1], patches[2], patches[3], patches[4], patches[5], patches[6], patches[7], mock.patch.object(
            batch_pdf, "process_one", side_effect=fake_process
        ):
            code = batch_pdf.run_batch(
                input_dir=self.input_dir,
                output_dir=self.notes_dir,
                prompt_path=self.prompt,
                output_ext="md",
                max_attempts=2,
                close_delay=0,
                keep_browser=True,
            )

        _assert(code == 2, f"Expected partial failure exit code 2, got {code}.")
        manifest = _load_json(self.notes_dir / "manifest.json")
        first = manifest["items"]["01_First.pdf::md"]
        second = manifest["items"]["02_Second.pdf::md"]
        _assert(first["status"] == "completed", "First job was not completed.")
        _assert(first["attempts"] == 1, "First job should require one attempt.")
        _assert(second["status"] == "failed", "Second job was not marked failed.")
        _assert(second["attempts"] == 2, "Second job should record both failed attempts.")
        _assert(Path(second["diagnostics"]).is_dir(), "Final diagnostics directory is missing.")
        _assert((self.notes_dir / "01_First.md").is_file(), "Valid first note is missing.")
        _assert(not (self.notes_dir / "02_Second.md").exists(), "Invalid note replaced the destination.")
        rejected = list((self.notes_dir / "_rejected").glob("02_Second-*.md"))
        _assert(len(rejected) == 2, "Each invalid attempt should preserve one rejected candidate.")
        summary = _load_json(self.logs_dir / "last_batch_summary.json")
        _assert(summary["failure_count"] == 1, "Batch summary did not record the failure.")
        _assert("02_Second.pdf" in summary["diagnostics"], "Summary is missing diagnostics path.")
        return "Partial failure returned 2; valid output survived; invalid candidates and final diagnostics were preserved."

    def _check_retry_and_resume(self) -> str:
        driver = FakeDriver()
        rerun: list[str] = []

        def fake_process(_driver, _prompt, input_path, output_dir, _model, **kwargs):
            rerun.append(input_path.name)
            output_path = output_dir / f"{input_path.stem}.{kwargs['output_ext'].lstrip('.')}"
            candidate = _write_candidate(
                self.workspace,
                "02_Second-retry.md",
                VALID_NOTE.format(title="Second Acceptance Topic"),
            )
            batch_pdf.common.save_artifact_download(candidate, output_path)
            return True

        patches = self._base_patches(driver)
        with patches[0], patches[1], patches[2], patches[3], patches[4], patches[5], patches[6], patches[7], mock.patch.object(
            batch_pdf, "process_one", side_effect=fake_process
        ):
            code = batch_pdf.run_batch(
                input_dir=self.input_dir,
                output_dir=self.notes_dir,
                prompt_path=self.prompt,
                output_ext="md",
                retry_failed=True,
                max_attempts=2,
                close_delay=0,
                keep_browser=True,
            )

        _assert(code == 0, f"Retry-failed run returned {code}.")
        _assert(rerun == ["02_Second.pdf"], f"Retry-failed ran unexpected jobs: {rerun}.")
        manifest = _load_json(self.notes_dir / "manifest.json")
        _assert(all(item["status"] == "completed" for item in manifest["items"].values()), "Not all jobs completed.")
        _assert(manifest["items"]["02_Second.pdf::md"]["attempts"] == 3, "Attempt history was not preserved.")

        with mock.patch.object(batch_pdf.common, "LOGS_DIR", self.logs_dir), mock.patch.object(
            batch_pdf.core, "LOG_FILE", self.workspace / "run.log"
        ), mock.patch.object(
            batch_pdf.common,
            "bootstrap_session",
            side_effect=AcceptanceFailure("Browser opened during unchanged Resume run."),
        ), mock.patch.object(
            batch_pdf, "process_one", side_effect=AcceptanceFailure("A completed job ran again.")
        ):
            code = batch_pdf.run_batch(
                input_dir=self.input_dir,
                output_dir=self.notes_dir,
                prompt_path=self.prompt,
                output_ext="md",
                close_delay=0,
            )

        _assert(code == 0, f"Unchanged Resume run returned {code}.")
        summary = _load_json(self.logs_dir / "last_batch_summary.json")
        _assert(len(summary["skipped"]) == 2, "Unchanged Resume did not skip both jobs.")
        return "--retry-failed ran only the failed job; a subsequent unchanged run skipped both jobs without a browser."

    def _check_pdf_book(self) -> str:
        pdf_dir = self.workspace / "outputs" / "pdfs"
        result = convert_md_to_pdf.batch_convert(self.notes_dir, pdf_dir)
        _assert(result.succeeded, f"PDF conversion failures: {result.failed}")
        _assert(len(result.created) == 2, f"Expected two topic PDFs, got {len(result.created)}.")

        topic_page_count = sum(len(PdfReader(path).pages) for path in result.created)
        combined_path = create_combined_pdf.create_combined(
            self.notes_dir,
            pdf_dir=pdf_dir,
            output_path=self.workspace / "outputs" / "COMBINED_NOTES.pdf",
            title="Phase 1 Acceptance Book",
        )
        reader = PdfReader(combined_path)
        index_page_count = len(reader.pages) - topic_page_count
        _assert(index_page_count >= 1, "Combined PDF is missing its index pages.")
        local_uris = [uri for uri in _uri_annotations(reader) if uri.casefold().startswith(("note:", "file:"))]
        _assert(not local_uris, f"Unresolved local URI annotations remain: {local_uris}")
        titles = _outline_titles(reader.outline)
        _assert(any("Study Index" in title for title in titles), "Study Index bookmark is missing.")
        _assert(any("First Acceptance Topic" in title for title in titles), "First topic bookmark is missing.")
        _assert(any("Second Acceptance Topic" in title for title in titles), "Second topic bookmark is missing.")
        _assert(reader.metadata.title == "Phase 1 Acceptance Book", "Combined PDF title metadata is incorrect.")
        return (
            f"Rendered 2 topic PDFs and a {len(reader.pages)}-page combined book "
            f"({index_page_count} index page(s)) with resolved local links and bookmarks."
        )


def run_acceptance(workspace: Path) -> dict:
    """Run all Phase 1 release checks and return a JSON-serializable report."""
    return Phase1Acceptance(workspace).run()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run browser-free Phase 1 release acceptance checks.")
    parser.add_argument(
        "--workdir",
        type=Path,
        help="Keep acceptance artifacts in this directory. By default a temporary directory is used.",
    )
    parser.add_argument(
        "--report",
        type=Path,
        default=Path("logs/phase1-acceptance.json"),
        help="JSON report path (default: logs/phase1-acceptance.json).",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    temporary = None
    if args.workdir is None:
        temporary = tempfile.TemporaryDirectory(prefix="note-maker-phase1-")
        workspace = Path(temporary.name)
    else:
        workspace = args.workdir

    try:
        report = run_acceptance(workspace)
        report_path = args.report.resolve()
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        for check in report["checks"]:
            marker = "PASS" if check["passed"] else "FAIL"
            print(f"[{marker}] {check['name']}: {check['details']}")
        print(f"Acceptance report: {report_path}")
        return 0 if report["passed"] else 2
    finally:
        if temporary is not None:
            temporary.cleanup()


if __name__ == "__main__":
    raise SystemExit(main())
