from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from uuid import uuid4

import tomli as tomllib

from .config import ConfigError, load_config_file, resolve_config

DEFAULT_CONFIG_FILENAME = "note-maker.toml"
SESSION_ALIAS_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
_TABLE_HEADER_RE = re.compile(r"(?m)^\s*\[[^\n]+\]\s*(?:#.*)?$")
_SESSIONS_HEADER_RE = re.compile(r"(?m)^\s*\[sessions\]\s*(?:#.*)?$")


@dataclass(frozen=True)
class ProjectInitSettings:
    input_dir: Path
    output_dir: Path
    prompt: Path
    output_ext: str = "md"
    browser_provider: str = "selenium"
    parallel_runs: int = 1


def default_config_path(*, cwd: Path | None = None) -> Path:
    return ((cwd or Path.cwd()) / DEFAULT_CONFIG_FILENAME).expanduser().resolve()


def _toml_string(value: str) -> str:
    # JSON basic strings use the same quoting/escaping forms needed here and
    # avoid introducing a second TOML writer dependency for this small file.
    return json.dumps(value, ensure_ascii=False)


def _portable_path(value: Path, *, base_dir: Path) -> str:
    path = Path(value).expanduser()
    if not path.is_absolute():
        return path.as_posix()
    resolved = path.resolve()
    try:
        return resolved.relative_to(base_dir.resolve()).as_posix()
    except ValueError:
        return str(resolved)


def _render_project_config(settings: ProjectInitSettings, *, base_dir: Path) -> str:
    return (
        "# Generated by `note-maker init`. Relative paths are resolved from this file.\n"
        "# Configuration presets belong under [profiles.*]. Browser session aliases\n"
        "# belong under [sessions] and point only to immutable snapshot identifiers.\n\n"
        "[runtime]\n"
        f"browser_provider = {_toml_string(settings.browser_provider)}\n"
        f"parallel_runs = {settings.parallel_runs}\n\n"
        "[commands.pdf]\n"
        f"input_dir = {_toml_string(_portable_path(settings.input_dir, base_dir=base_dir))}\n"
        f"output_dir = {_toml_string(_portable_path(settings.output_dir, base_dir=base_dir))}\n"
        f"prompt = {_toml_string(_portable_path(settings.prompt, base_dir=base_dir))}\n"
        f"output_ext = {_toml_string(settings.output_ext)}\n"
        "resume = true\n\n"
        "[sessions]\n"
    )


def _write_text_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.parent / f".{path.name}.{uuid4().hex}.tmp"
    try:
        fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def write_project_config(
    path: Path,
    settings: ProjectInitSettings,
    *,
    force: bool = False,
) -> Path:
    path = Path(path).expanduser().resolve()
    if path.exists() and not force:
        raise ConfigError(
            f"Configuration already exists: {path}. Re-run with --force only if replacement is intended."
        )
    text = _render_project_config(settings, base_dir=path.parent)
    # Validate through the existing resolver before replacing the real file.
    temporary = path.parent / f".{path.name}.validate.{uuid4().hex}.toml"
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        temporary.write_text(text, encoding="utf-8", newline="\n")
        resolve_config("pdf", config_path=temporary, environ={}, cwd=path.parent)
    finally:
        temporary.unlink(missing_ok=True)
    _write_text_atomic(path, text)
    return path


def _session_aliases(document: Any, *, path: Path) -> dict[str, str]:
    if not isinstance(document, dict):
        raise ConfigError(f"Configuration file {path} must contain a TOML document.")
    raw = document.get("sessions", {})
    if not isinstance(raw, dict):
        raise ConfigError("sessions must be a TOML table.")
    aliases: dict[str, str] = {}
    for alias, snapshot in raw.items():
        name = str(alias)
        if not SESSION_ALIAS_RE.fullmatch(name):
            raise ConfigError(
                f"Session alias {name!r} must use only letters, numbers, '.', '_' or '-'."
            )
        if not isinstance(snapshot, str) or not snapshot.strip():
            raise ConfigError(f"sessions.{name} must be a non-empty snapshot identifier string.")
        aliases[name] = snapshot.strip()
    return aliases


def load_session_aliases(path: Path) -> dict[str, str]:
    path = Path(path).expanduser().resolve()
    return _session_aliases(dict(load_config_file(path)), path=path)


def resolve_session_reference(path: Path, reference: str) -> tuple[str | None, str]:
    aliases = load_session_aliases(path)
    snapshot = aliases.get(reference)
    return (reference, snapshot) if snapshot is not None else (None, reference)


def _replace_or_append_session(text: str, *, alias: str, snapshot_id: str) -> str:
    assignment = f"{alias} = {_toml_string(snapshot_id)}"
    header = _SESSIONS_HEADER_RE.search(text)
    if header is None:
        prefix = text.rstrip()
        return f"{prefix}\n\n[sessions]\n{assignment}\n" if prefix else f"[sessions]\n{assignment}\n"

    body_start = header.end()
    next_header = _TABLE_HEADER_RE.search(text, body_start)
    body_end = next_header.start() if next_header is not None else len(text)
    body = text[body_start:body_end]
    assignment_re = re.compile(rf"(?m)^\s*{re.escape(alias)}\s*=.*$")
    if assignment_re.search(body):
        body = assignment_re.sub(assignment, body, count=1)
    else:
        if body and not body.endswith("\n"):
            body += "\n"
        body += f"{assignment}\n"
    return text[:body_start] + body + text[body_end:]


def set_session_alias(path: Path, alias: str, snapshot_id: str) -> None:
    path = Path(path).expanduser().resolve()
    if not SESSION_ALIAS_RE.fullmatch(alias):
        raise ConfigError(
            f"Session alias {alias!r} must use only letters, numbers, '.', '_' or '-'."
        )
    snapshot_id = snapshot_id.strip()
    if not snapshot_id:
        raise ConfigError("Snapshot identifier may not be empty.")
    if not path.is_file():
        raise ConfigError(f"Configuration file does not exist: {path}. Run `note-maker init` first.")

    current = path.read_text(encoding="utf-8")
    # Parse the existing file before and after the targeted section edit so a
    # session alias can never corrupt unrelated project configuration.
    document = tomllib.loads(current)
    _session_aliases(document, path=path)
    updated = _replace_or_append_session(current, alias=alias, snapshot_id=snapshot_id)
    parsed = tomllib.loads(updated)
    aliases = _session_aliases(parsed, path=path)
    if aliases.get(alias) != snapshot_id:
        raise ConfigError(f"Could not persist session alias {alias!r} safely.")
    _write_text_atomic(path, updated)
