from __future__ import annotations

from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from .models import (
    BrowserHealth,
    BrowserLaunchOptions,
    DownloadRequest,
    ResponseWaitRequest,
    UploadRequest,
)


@runtime_checkable
class BrowserSession(Protocol):
    """High-level browser session consumed by batch orchestration.

    Batch code must use this contract rather than Selenium/Playwright locators or
    raw driver methods. ``raw_handle`` exists only for transitional adapters.
    """

    provider_name: str

    @property
    def raw_handle(self) -> object: ...

    def is_alive(self) -> bool: ...
    def health(self) -> BrowserHealth: ...
    def recover(self, reason: str = "") -> bool: ...
    def close(self) -> None: ...
    def set_window_size(self, width: int, height: int) -> None: ...
    def navigate(self, url: str) -> None: ...
    def wait_until_logged_in(self, timeout: int = 600) -> None: ...
    def start_new_chat(self) -> None: ...
    def select_model(self, model: str | None) -> None: ...
    def assistant_message_count(self) -> int: ...
    def upload(self, request: UploadRequest) -> None: ...
    def send_message(self, text: str) -> None: ...
    def wait_for_response(self, request: ResponseWaitRequest) -> None: ...
    def snapshot_downloads(self) -> Any: ...
    def resolve_download(self, request: DownloadRequest) -> Path | None: ...
    def latest_assistant_text(self) -> str: ...
    def save_screenshot(self, path: Path) -> bool: ...
    def get_page_source(self) -> str: ...
    def get_cookies(self) -> Sequence[Mapping[str, Any]]: ...
    def delete_cookie(self, name: str) -> None: ...


@runtime_checkable
class BrowserProvider(Protocol):
    """Factory and adapter contract for a concrete browser engine."""

    name: str

    def open_session(self, options: BrowserLaunchOptions | None = None) -> BrowserSession: ...
    def wrap_handle(self, handle: object) -> BrowserSession: ...
